spring:
  liquibase:
    change-log: db/changelog/db-changelog-master.xml
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
  security:
    jwt:
      secret: ${JWT_SECRET}
app:
  openai:
    responses-url: https://api.openai.com/v1/responses
    model: gpt-5-mini
